/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { GroupCreateNestedManyWithoutTeachersInput } from "./GroupCreateNestedManyWithoutTeachersInput";
import { Type } from "class-transformer";
import { LessonCreateNestedManyWithoutTeachersInput } from "./LessonCreateNestedManyWithoutTeachersInput";
import { ScheduleCreateNestedManyWithoutTeachersInput } from "./ScheduleCreateNestedManyWithoutTeachersInput";

@InputType()
class TeacherCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  hours?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  room?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subject?: string | null;

  @ApiProperty({
    required: false,
    type: () => GroupCreateNestedManyWithoutTeachersInput,
  })
  @ValidateNested()
  @Type(() => GroupCreateNestedManyWithoutTeachersInput)
  @IsOptional()
  @Field(() => GroupCreateNestedManyWithoutTeachersInput, {
    nullable: true,
  })
  groups?: GroupCreateNestedManyWithoutTeachersInput;

  @ApiProperty({
    required: false,
    type: () => LessonCreateNestedManyWithoutTeachersInput,
  })
  @ValidateNested()
  @Type(() => LessonCreateNestedManyWithoutTeachersInput)
  @IsOptional()
  @Field(() => LessonCreateNestedManyWithoutTeachersInput, {
    nullable: true,
  })
  lessons?: LessonCreateNestedManyWithoutTeachersInput;

  @ApiProperty({
    required: false,
    type: () => ScheduleCreateNestedManyWithoutTeachersInput,
  })
  @ValidateNested()
  @Type(() => ScheduleCreateNestedManyWithoutTeachersInput)
  @IsOptional()
  @Field(() => ScheduleCreateNestedManyWithoutTeachersInput, {
    nullable: true,
  })
  schedules?: ScheduleCreateNestedManyWithoutTeachersInput;
}

export { TeacherCreateInput as TeacherCreateInput };
