/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { GroupUpdateManyWithoutTeachersInput } from "./GroupUpdateManyWithoutTeachersInput";
import { Type } from "class-transformer";
import { LessonUpdateManyWithoutTeachersInput } from "./LessonUpdateManyWithoutTeachersInput";
import { ScheduleUpdateManyWithoutTeachersInput } from "./ScheduleUpdateManyWithoutTeachersInput";

@InputType()
class TeacherUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  hours?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  room?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subject?: string | null;

  @ApiProperty({
    required: false,
    type: () => GroupUpdateManyWithoutTeachersInput,
  })
  @ValidateNested()
  @Type(() => GroupUpdateManyWithoutTeachersInput)
  @IsOptional()
  @Field(() => GroupUpdateManyWithoutTeachersInput, {
    nullable: true,
  })
  groups?: GroupUpdateManyWithoutTeachersInput;

  @ApiProperty({
    required: false,
    type: () => LessonUpdateManyWithoutTeachersInput,
  })
  @ValidateNested()
  @Type(() => LessonUpdateManyWithoutTeachersInput)
  @IsOptional()
  @Field(() => LessonUpdateManyWithoutTeachersInput, {
    nullable: true,
  })
  lessons?: LessonUpdateManyWithoutTeachersInput;

  @ApiProperty({
    required: false,
    type: () => ScheduleUpdateManyWithoutTeachersInput,
  })
  @ValidateNested()
  @Type(() => ScheduleUpdateManyWithoutTeachersInput)
  @IsOptional()
  @Field(() => ScheduleUpdateManyWithoutTeachersInput, {
    nullable: true,
  })
  schedules?: ScheduleUpdateManyWithoutTeachersInput;
}

export { TeacherUpdateInput as TeacherUpdateInput };
